### ISSUE TITLE
auto complete does not work when type definition is included

### ISSUE THREAD

**Issue by JHenneberg** [hansec/fortran-language-server#75] opened 2019-01-31 11:39 UTC
Hey,

unfortunately the auto complete does not work when type definition is included. Here is a minimal example:

.fortls:
```JSON
{
  "mod_dirs": [
    "INCL"
  ],
  "excl_paths": [".vs", "Debug"],
  "excl_suffixes": [".u2d", ".vfproj", ".sln", ".txt"],
  "lowercase_intrinsics": false,
  "debug_log": false
}
```

PROGRAM.f90
```FORTRAN
PROGRAM minimal
  IMPLICIT NONE

  INCLUDE 'INCL/TYPE.f90'

  TYPE(tExample) :: myExample

END PROGRAM
```

TYPE.f90
```FORTRAN
TYPE :: tExample
  REAL(8) :: X
  REAL(8) :: Y
END TYPE
```

When you use now tExample in the program scope auto complete does not work.

folder structure is
```
|->myProject
    |->.fortls
    |->PROGRAM.f90
    |->INCL
        |->TYPE.f90
```

**Comment by hansec** [comment] 2019-01-31 15:43
Thanks for the report. Unfortunately, I am not able to reproduce this using the example code you provided with either VSCode or Atom. Everything works as expected for me. What editor/OS are you using?

**Comment by hansec** [comment] 2019-01-31 16:56
Does goto definition work for `tExample` when you have the include statement active?

**Comment by hansec** [comment] 2019-01-31 18:10
Ok, I was able to reproduce this on WIN7 with Atom. It looks like Atom started passing forward slashes in some situations on Windows, which is breaking things. I will look into this some more and figure out the best plan of attack. Thanks for the report!

**Comment by hansec** [comment] 2019-01-31 20:38
Ok, I believe I found a fix for this. If possible, can you checkout the current master and see if it solves your problem? Thanks again for the report!

**Closed** 2019-01-31 20:38 UTC
Labels: bug
