### ISSUE TITLE
Resolve names from associate statement

### ISSUE THREAD

**Issue by mscfd** [hansec/fortran-language-server#101] opened 2019-03-27 08:26 UTC
Variable given by an associate statement are not recognised (e.g. for completion). Example, where the first request works, but the second and third fail:
```fortls --debug_rootpath . --debug_completion --debug_filepath test7.f90 --debug_line 29 --debug_char 26```

```fortls --debug_rootpath . --debug_completion --debug_filepath test7.f90 --debug_line 30 --debug_char 19```

```fortls --debug_rootpath . --debug_completion --debug_filepath test7.f90 --debug_line 31 --debug_char 18```

test7.f90:
```
module mod

implicit none
private

type, public :: t
   integer :: my_var
contains
   procedure :: my_sub
end type t

type, public :: s
   type(t) :: xxx
end type s

contains

   subroutine my_sub(self, My_Var)
      class(t), intent(in) :: self
      self%my_var = My_Var
   end subroutine my_sub


   subroutine test()
      type(s) :: abcdef
      integer :: j

      associate(xxx => abcdef%xxx)
         call abcdef%xxx%
         call xxx%
         j = xxx%
      end associate
   end subroutine test

end module mod
```

**Comment by mscfd** [comment] 2019-03-28 14:00
Here is a similar problem, where looking for references does not show references within associate blocks:
```fortls --debug_rootpath . --debug_reference --debug_filepath testA.f90 --debug_line 27 --debug_char 20```

```fortls --debug_rootpath . --debug_reference --debug_filepath testA.f90 --debug_line 27 --debug_char 32```

The first request is answered well, although I would think that the line "r = 1.0" should be included in the results list, as the associate acts like an alias. Also this would make it more consistent with the second request, which should include the line "s%some_param = 5" in its result.

testA.f90:
```
module mod

implicit none

type, public :: t
   integer :: some_param
end type t

type, public :: s
   type(t) :: a
   real :: some_real
end type s

contains

subroutine sub(x)
   type(s), intent(inout) :: x
   associate(s => x%a, &
             r => x%some_real)
      r = 1.0
      s%some_param = 5
   end associate
end subroutine sub

subroutine app()
   type(s) :: u
   print *, u%some_real, u%a%some_param
end subroutine app

end module mod
```

**Comment by mscfd** [comment] 2019-04-03 06:18
I have just checked it a bit. It looks like there is serious performance problem. Moreover after I got a timeout the server trips and subsequent simple answers lock emacs. From "top" I can see that the python fortls process stops to consume CPU usage some time after emacs aborted the reference request with a timeout. But even after CPU usage is down, the server does not behave well anymore.
I am using and testing it with a 300k+ project, so there is a fair amount of scanning to do. The reference requests in general are rather slow (1-3s) on this medium sized project. I think that the method get_all_references might be easily parallelised? But besides that, the recent commits have somehow broken the performance of reference requests. For one case I checked Version 1.7.3 takes 1-2s to answer the reference request for my_method at "call a%b%c%my_method(...)", where branch 1.8 takes roughly 40s (after I have increase timeout threshold). Otherwise the request for the two call lines take about the same time
```
call a%b%c%my_method(...)
associate(x => a%b%c)
   call x%my_method(...)
end_associate
```

**Comment by mscfd** [comment] 2019-04-03 06:44
After some more testing (and watching with top), I can see that 1.8 parses (in parallel) pretty quickly and then the server process remains at 100% for a very long time (roughly one minute or even more). Initialisation of 1.7 seems to be much quicker. At first reference requests are rejected ("not supported..."), but it looks like that the initialisation process is still running when reference requests are finally accepted but they are not readily answered. If I wait until the server python process goes to sleep, then answer times for reference requests are short (a few seconds).
Also after opening a new fortran file from the project, fortls seems to be locked down for quite some time, also locking emacs.

**Comment by hansec** [comment] 2019-04-03 12:50
Whoa, that doesn't sound good. Can you do some more testing to isolate which commit in the v1.8 branch introduces this issue? I suspect it would be the associate commit (28e37cc).

**Comment by mscfd** [comment] 2019-04-03 13:40
I will check tomorrow. I definitely would like to enable debug_log, and possible insert some "print date" lines in fortls, so that I can narrow down the problem using emacs log buffer.

**Comment by mscfd** [comment] 2019-04-04 11:09
I have done some testing. It indeed seems to be caused by commit 28e37cc. It looks like that there are at least two places where performance has significantly degraded.

Not all things listed below might be relevant, but might help to follow the process:

* If I uncomment the multiprocess.pool part and do the init_file loop single threaded, then the next loop hangs at the first item from results.items(). Not sure whether this is relevant. It is at least strange.

* With commit 28e37cc, the last loop in workspace_init takes really long:
```
        # Update inheritance
        for key in self.obj_tree:
            self.obj_tree[key][0].resolve_inherit(self.obj_tree)
            self.obj_tree[key][0].resolve_link(self.obj_tree)
```

* Once workspace_init is finished the end of  ```serve_initialize(self, request)```, from which workspace_init was called, is reached quickly. emacs also shows the messages from the post_messages buffer, in particular "FORTLS initialization complete". So I guess the else branch in the 
while loop of the server run method has been processed.

* From further test output I can see that after initialisation more messages are send back and forth (didOpen, initialized etc.) Everything looks fine. At the end a "textDocument/publishDiagnostics" is send to emacs (without any request from emacs as far as I can see). It looks like that this takes a short time with eef6764, but a long time with  28e37cc. It is the python process at 100% I have observed in top. Once the diagonistics has been published, there are no active python process anymore.

**Comment by mscfd** [comment] 2019-04-04 12:14
Ups, "uncomment the multiprocess.pool ..." should be "comment out the multiprocess.pool...".

**Comment by hansec** [comment] 2019-04-04 12:46
Ok, I think the issue is with additional links required during the `resolve_link(self.obj_tree)` phase. Since associate statements require resolving the link (ex. `x => a%b%c`) if there are a lot of these it could slow down the linking stage where you saw a big slow down. Does the code you are testing on have lots of "ASSOCIATE" statements?

Similarly, the `textDocument/publishDiagnostics` request is only for the "opened" file. Does this phase take more or less time if you test by opening a file with or without a lot of "ASSOCIATE" statements?

I have a couple of ideas to speed these phase up, which I will try when I get a chance.

**Comment by hansec** [comment] 2019-04-04 12:47
Also, did commit (053984a) have any effect on the initialization time?

**Comment by hansec** [comment] 2019-04-04 15:49
Ok, I think the commits above should help. It certainly made reference searching much faster on my projects.

**Comment by mscfd** [comment] 2019-04-05 04:53
The file I have tested with had two associate statements. I just tested with a file without those blocks (and with only a small DAC of dependencies), and the init step as well as the diagnostic step take a long time, too. (Currently we have about 1200 "associate(...)" blocks (sometimes even nested), but this will further rise, as we have adopted the construct not that long ago.)

With the new commits, the first critical loop at the end of workspace_init ("# Update inheritance") now takes about 4s on the module I have test with, which is much faster than before. The publishDiagnostic step now takes about 1s, so much faster as well. 

Requesting references for my_method (where the real code looks pretty much like the example below), the timing is about 0.8s both within the line before the associate as well as for the second line within the associate (there are somewhat more than 150 references all over the place):
```
call a%b%c%my_method(...)
associate(x => a%b%c)
   call x%my_method(...)
end_associate
```

So I would think that his looks pretty good (except maybe for really big multi-million line codes). Parallelisation of the reference request might still be benefical (at least parallelisation of get_all_references looks easy enough?).

Great work!

BTW: Do you have any idea why omitting the worksharing pool for parsing breaks the subsequent loop?

**Comment by hansec** [comment] 2019-04-05 17:54
Great. Thanks for all the information and thoroughly testing everything out!

As for the the issue with serial parsing, I am not exactly sure but did you replace the `result_obj = result.get()` line with just `result_obj = result`? The `.get()` part is for retrieving things from the thread pool, usually leaving it in causes an error but maybe it could also cause things to hang. There is certainly no reason why a single thread shouldn't work, but Python's threading is awkward so there are a lot of changes required to switch back and forth between multi and single threading.

**Closed** 2019-04-05 18:08 UTC
Labels: enhancement

**Comment by mscfd** [comment] 2019-04-08 04:45
I have missed that apply_async returns an AsyncResult object and hence missed that get(). I guess this has indeed caused the hang. But I am still surprised that it did not fail, e.g. due to missing get() method.
