### ISSUE TITLE
fortls is bit slow to start

### ISSUE THREAD

**Issue by rudrab** [hansec/fortran-language-server#123] opened 2019-06-28 18:39 UTC
Hi, 
I am using `fortls` in vim8, as supported by `coc.nvim`.
My minimal vimrc is:

```
"General "{{{
set nocompatible                     "  because vim is not vi
set spell spl=en_us                  "  Set Spell
syntax enable
set tabstop=2                        "  Tabs width
set shiftwidth=2                     "  Default shift width for indents
set softtabstop=2
set expandtab                        "  but tabs are actually space
set backspace=eol,start,indent       "  Configure backspace so it acts as it should act
set encoding=utf8
set nu                               "  show line numbers
set noshowmode
"}}}


" VimPlug {{{
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin('~/.vim/plugged')
 Plug 'neoclide/coc.nvim'  , {'do': './install.sh nightly'}
call plug#end()
filetype plugin indent on
"}}}

"LANGUAGE SPECIFIC STAFFS{{{
  "Fortran {{{
    augroup FT_Fortran
      au!
      let fortran_do_enddo = 1
      let fortran_more_precise = 1
      let fortran_free_source = 1
      let fortran_have_tabs = 1
    augroup END
  "}}}
"}}}

" LANGUAGE SERVER{{{
let g:coc_start_at_startup = 0
augroup coc
  autocmd!
  autocmd VimEnter * :silent CocStart
augroup end
let g:coc_user_config = {
      \   'languageserver': {
      \     'fortran': {
      \       'command': 'fortls',
      \       'args': ['--lowercase_intrinsics'],
      \       'filetypes': ['fortran'],
      \       'rootPatterns': ['.fortls', '.git/'],
      \     }
      \   }
      \ }
" }}}

```

The problem is, it is taking some time to start completion, say, 30-40sec after opening a file.
Is it know or there is some problem in my configuration? Kindly let me know.

**Comment by hansec** [comment] 2019-07-01 16:21
Thanks for the report.

First, can you do a [debug run from the command line](https://github.com/hansec/fortran-language-server/wiki/Debugging-server-initialization-errors) using the same project to isolate if this is an error with the vim setup or the language server? Likely, this is a language server issue and not Vim related.

If the debug initialization is slow as well, can you give me a little more info on the codebase? Is this a large project and is it open source so that I can test out/debug the issue?

**Comment by hansec** [comment] 2019-07-04 15:47
I just fixed [an issue](https://github.com/hansec/fortran-language-server/issues/122) that may be related. Can you see if release `v1.9.1` improves things?

**Comment by rudrab** [comment] 2019-07-05 11:08
Unfortunately no! As described in that issue, I am also having this problem in new files only. If I reopen an existing file, there is no issue.

**Comment by hansec** [comment] 2019-07-05 16:51
Ok, have you been able to try running debug initialization to see if server startup is slow outside of Vim?

**Comment by rudrab** [comment] 2019-07-05 19:30
you mean `fortls --debug_rootpath=.`? This I have run, and I haven't found anything unusual. 

I am just trying a new `hello world` inside various directory. Obviously, the above command is taking more time to complete if I am working in `$HOME`, and very fast when inside an almost empty folder.

**Comment by hansec** [comment] 2019-07-05 19:38
Run that command but with 'debug_rootpath' set to the directory where the file you are opening in Vim is located. The point is to see if the initialization of the server is slow on its own or only when used with Vim. If running 'fortls' alone completes fast, but Vim is still slow using the same directory this indicates an issue with how Vim interacts with the server not the server itself.

**Comment by rudrab** [comment] 2019-07-07 11:52
@hansec: sorry for the late reply. `fortls --debug_rootpath=.` i.e. I am running the debug in my current directory, where I am opening the file. vim is taking much more time to start completion than the command to complete.

**Comment by hansec** [comment] 2019-07-07 19:11
Ok, then that is something related to how Vim is starting the server or perhaps how it is setting up its own completion internally. Do you see this behavior with any other language servers in Vim?

**Comment by rudrab** [comment] 2019-07-08 06:14
No. I use python and LaTeX, and both of them are very fast.

**Comment by rudrab** [comment] 2019-07-08 06:56
Also, as I said before, when I reopen an existing file, it's very fast. The problem only comes when I create a new file. any clue?

**Comment by hansec** [comment] 2019-07-08 15:57
This definitely appears to be an internal issue with your Vim plugin/configuration not the language server. As I don't use Vim personally I can't really help you out there. I know people have had success with https://github.com/autozimu/LanguageClient-neovim, but other than that I am not sure. Sorry about that.

**Comment by hansec** [comment] 2019-07-09 13:39
> You have to save the file before open it, some language server have this kind of issue
> because vscode always create file before open

Does this fix the issue for you? If so, can you retrieve the log of language server messages? As long as the order of requests `coc.nvim` emits is consistent I should be able to fix this on the language server end so you don't need to do anything "special".

**Comment by rudrab** [comment] 2019-07-09 14:25
@hansec: yes, as I said, if I open, write something, write-quit and reopen it, everything is fine. 

 **when new file opened, and something is written to it:**
[forls_debug.log](https://paste.fedoraproject.org/paste/QVLTT1He40GJHPqfNNYO~Q)

CocInfo:
```
vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 28 2019 09:32:51)
node version: v10.16.0
coc.nvim version: 0.0.72-2454a4d1e0
term: dumb
platform: linux

## Messages
Messages maintainer: Mike Williams <mrw@eandem.co.uk>
[coc.nvim] Change request failed for unknown file "/home/rudra/Projects/i.f90"
[coc.nvim] Change request failed for unknown file "/home/rudra/Projects/i.f90"
The only match
The only match
The only match
The only match
[coc.nvim] Change request failed for unknown file "/home/rudra/Projects/i.f90"
[coc.nvim] Change request failed for unknown file "/home/rudra/Projects/i.f90"
[coc.nvim] Change request failed for unknown file "/home/rudra/Projects/i.f90"
[coc.nvim] Change request failed for unknown file "/home/rudra/Projects/i.f90"
[coc.nvim] Change request failed for unknown file "/home/rudra/Projects/i.f90"
"i.f90" [New] 9L, 173C [w]
## Output channel: languageserver.fortran

Change request failed for unknown file "/home/rudra/Projects/i.f90"
Change request failed for unknown file "/home/rudra/Projects/i.f90"
Change request failed for unknown file "/home/rudra/Projects/i.f90"
Change request failed for unknown file "/home/rudra/Projects/i.f90"
Change request failed for unknown file "/home/rudra/Projects/i.f90"
Change request failed for unknown file "/home/rudra/Projects/i.f90"
Change request failed for unknown file "/home/rudra/Projects/i.f90"
```

**After write-quit and reopen the same file:** (I tried completion of `use`)
[fortls_debug.log](https://paste.fedoraproject.org/paste/lDnxj5ZHnFU4rKYX2-XjqQ) 
(NB: I have deleted the fortls_debug.log generated on the previous step)
```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 28 2019 09:32:51)
node version: v10.16.0
coc.nvim version: 0.0.72-2454a4d1e0
term: dumb
platform: linux

## Messages
Messages maintainer: Mike Williams <mrw@eandem.co.uk>
"i.f90" 10L, 179C
[coc.nvim] FORTLS debugging enabled
match 1 of 2
match 1 of 2
match 1 of 5
match 1 of 5
match 1 of 4
match 1 of 4
match 1 of 2
match 1 of 2
match 1 of 2
match 2 of 2
Unclassifiable statement at (1)
Unclassifiable statement at (1)
"i.f90" 10L, 195C [w]
```

Or do you mean something else by

**Comment by rudrab** [comment] 2019-07-09 14:26
> Does this fix the issue for you? If so, can you retrieve the log of language server messages? As long as the order of requests `coc.nvim` emits is consistent I should be able to fix this on the language server end so you don't need to do anything "special".

@hansec L Thanks a lot for your time and help.

**Comment by hansec** [comment] 2019-07-09 15:40
Ok, I just pushed a possible fix to the `allow_create_on_change` branch (see commit above). Can you check it out and see if it fixes the issue? Thanks!

**Comment by hansec** [comment] 2019-07-09 16:04
Actually, the `allow_empty_open` branch is a better fix for this issue. Can you test it when you get a chance and let me know if it fixes this issue? Thanks!

**Comment by rudrab** [comment] 2019-07-09 18:00
@hansec : I have updated as:
`sudo pip3 install git+https://github.com/hansec/fortran-language-server@allow_empty_open --upgrade`
There is no change in behaviour, except `CocInfo` is writing the same line many times more, and this is
[fortls_debug.log](https://paste.fedoraproject.org/paste/~3kMBZFLGcRiVlk8Ve8FuA)

**Comment by hansec** [comment] 2019-07-09 18:16
Ooops, sorry about that there was a typo that I just fixed. That'll teach me to get lazy on the test cases. Can you update the `allow_empty_open ` and try it again?

**Comment by rudrab** [comment] 2019-07-09 18:37
wow! thanks a lot! Now it is working awesome.

**Comment by hansec** [comment] 2019-07-09 18:42
Great, it is in `v1.10` now so it will be included in the next release. You should automatically get a notification when the issue is closed by that merge.

**Closed** 2019-07-09 18:56 UTC
Labels: bug, downstream
